### ISSUE TITLE
Building for deployment

### ISSUE THREAD

**Issue by fils** [zazuko/openlayers-elements#33]
So this is a very basic question but I'm rather new to leveraging yarn in work flows.

I am able to clone, and build and run this repo.   I can navigate through and run the demos like the simple marker demo.  

However, how do then build a self contained pack (web pack?) that I can call from a page that is using one of these components that I server from my simple web server.  

Any guidance, links for help on how to deploy to servers would be appreciated!

**Comment by tpluscode** [comment]
Hi @fils. Indeed this repository uses yarn but I have mostly reverted back to npm these days. It is not really important which tool you use.

As for actual packaging, to have a closer look at how the project in `docs` directory is set up. It uses [Open Web Component](https://open-wc.org) to reduce boilerplate needed to build, test and deploy an application. They have pre-built packages for [webpack](https://open-wc.org/building/building-webpack.html) and [rollup](https://open-wc.org/building/building-rollup.html).

I recommend that you start with their guides and use the `npm init @open-wc` command to get started if you don't have a project already.

That being said, there is nothing really specific in the map elements which should affect your workflow. You may need polyfills to support some browsers/features in general but otherwise this is just JS code like any other: Import in your code and use in HTML.

Let me know if you have some more questions. I will be happy to help but it sounds like you should focus on web components to get your answers. I recommend the [Polymer slack](https://join.slack.com/t/polymer/shared_invite/enQtNTAzNzg3NjU4ODM4LTkzZGVlOGIxMmNiMjMzZDM1YzYyMzdiYTk0YjQyOWZhZTMwN2RlNjM5ZDFmZjMxZWRjMWViMDA1MjNiYWFhZWM).
